### ISSUE TITLE
[BUG] - Generate personnummer always adds +1 to month

### ISSUE THREAD

**Issue by TheConfuser** [personnummer/personnummer.github.io#55]
When generating a personnummer using the website, it always adds +1 to the month. 

If generating using year 2021, month 02 and day 6, I will get 20210306 instead of 20210206. For month 1, it sets 02. If month 12 (december), it sets 01, so it loops around since it adds +1 to all. 

I'm not sure but it might be this today.getMonth() + 1 that is the issue. 
https://github.com/personnummer/personnummer.github.io/blob/7d6059e5e20240cfd12bb15eba8dc563f08eafc0/src/components/Generate/index.js#L13

![image](https://user-images.githubusercontent.com/5488143/107039910-cadf2180-67be-11eb-913a-bb3a88b6790e.png)

**Comment by frozzare** [comment]
Thanks, fixed now!
